// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: sidecar/sidecar.proto

package sidecar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*RegisterRequest_Init
	//	*RegisterRequest_Heartbeat
	Type          isRegisterRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_sidecar_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetType() isRegisterRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *RegisterRequest) GetInit() *Init {
	if x != nil {
		if x, ok := x.Type.(*RegisterRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *RegisterRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Type.(*RegisterRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isRegisterRequest_Type interface {
	isRegisterRequest_Type()
}

type RegisterRequest_Init struct {
	Init *Init `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type RegisterRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*RegisterRequest_Init) isRegisterRequest_Type() {}

func (*RegisterRequest_Heartbeat) isRegisterRequest_Type() {}

type Init struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// svcid is the load-balancing identity. Multiple replicas with the
	// same svcid share queue-group load balancing on unary RPCs.
	Svcid string `protobuf:"bytes,1,opt,name=svcid,proto3" json:"svcid,omitempty"`
	// upstream is the local gRPC server address (host:port) the sidecar
	// forwards incoming NATS calls to.
	Upstream string `protobuf:"bytes,2,opt,name=upstream,proto3" json:"upstream,omitempty"`
	// services are the fully-qualified proto service names the local app
	// serves (e.g. "echo.Echo", "payments.PaymentService"). The sidecar
	// opens one subscription per service.
	Services      []string `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Init) Reset() {
	*x = Init{}
	mi := &file_sidecar_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init) ProtoMessage() {}

func (x *Init) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init.ProtoReflect.Descriptor instead.
func (*Init) Descriptor() ([]byte, []int) {
	return file_sidecar_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *Init) GetSvcid() string {
	if x != nil {
		return x.Svcid
	}
	return ""
}

func (x *Init) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *Init) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

type Heartbeat struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ClientTimestampUnixNano int64                  `protobuf:"varint,1,opt,name=client_timestamp_unix_nano,json=clientTimestampUnixNano,proto3" json:"client_timestamp_unix_nano,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_sidecar_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_sidecar_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetClientTimestampUnixNano() int64 {
	if x != nil {
		return x.ClientTimestampUnixNano
	}
	return 0
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*RegisterResponse_Registered
	//	*RegisterResponse_Error
	//	*RegisterResponse_HeartbeatAck
	Type          isRegisterResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_sidecar_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetType() isRegisterResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *RegisterResponse) GetRegistered() *Registered {
	if x != nil {
		if x, ok := x.Type.(*RegisterResponse_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *RegisterResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Type.(*RegisterResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *RegisterResponse) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Type.(*RegisterResponse_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

type isRegisterResponse_Type interface {
	isRegisterResponse_Type()
}

type RegisterResponse_Registered struct {
	Registered *Registered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type RegisterResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type RegisterResponse_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,3,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

func (*RegisterResponse_Registered) isRegisterResponse_Type() {}

func (*RegisterResponse_Error) isRegisterResponse_Type() {}

func (*RegisterResponse_HeartbeatAck) isRegisterResponse_Type() {}

type Registered struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nid is the sidecar-assigned per-replica identifier used as the
	// <nid> segment of streaming subjects. The app should pass this to
	// peers that need to target it specifically (e.g. via callers'
	// x-nats-target-nid header).
	Nid           string `protobuf:"bytes,1,opt,name=nid,proto3" json:"nid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registered) Reset() {
	*x = Registered{}
	mi := &file_sidecar_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registered) ProtoMessage() {}

func (x *Registered) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registered.ProtoReflect.Descriptor instead.
func (*Registered) Descriptor() ([]byte, []int) {
	return file_sidecar_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *Registered) GetNid() string {
	if x != nil {
		return x.Nid
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_sidecar_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatAck struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ServerTimestampUnixNano int64                  `protobuf:"varint,1,opt,name=server_timestamp_unix_nano,json=serverTimestampUnixNano,proto3" json:"server_timestamp_unix_nano,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_sidecar_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_sidecar_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatAck) GetServerTimestampUnixNano() int64 {
	if x != nil {
		return x.ServerTimestampUnixNano
	}
	return 0
}

var File_sidecar_sidecar_proto protoreflect.FileDescriptor

const file_sidecar_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x15sidecar/sidecar.proto\x12\asidecar\"r\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\x04init\x18\x01 \x01(\v2\r.sidecar.InitH\x00R\x04init\x122\n" +
	"\theartbeat\x18\x02 \x01(\v2\x12.sidecar.HeartbeatH\x00R\theartbeatB\x06\n" +
	"\x04type\"T\n" +
	"\x04Init\x12\x14\n" +
	"\x05svcid\x18\x01 \x01(\tR\x05svcid\x12\x1a\n" +
	"\bupstream\x18\x02 \x01(\tR\bupstream\x12\x1a\n" +
	"\bservices\x18\x03 \x03(\tR\bservices\"H\n" +
	"\tHeartbeat\x12;\n" +
	"\x1aclient_timestamp_unix_nano\x18\x01 \x01(\x03R\x17clientTimestampUnixNano\"\xbf\x01\n" +
	"\x10RegisterResponse\x125\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2\x13.sidecar.RegisteredH\x00R\n" +
	"registered\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x16.sidecar.ErrorResponseH\x00R\x05error\x12<\n" +
	"\rheartbeat_ack\x18\x03 \x01(\v2\x15.sidecar.HeartbeatAckH\x00R\fheartbeatAckB\x06\n" +
	"\x04type\"\x1e\n" +
	"\n" +
	"Registered\x12\x10\n" +
	"\x03nid\x18\x01 \x01(\tR\x03nid\")\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"K\n" +
	"\fHeartbeatAck\x12;\n" +
	"\x1aserver_timestamp_unix_nano\x18\x01 \x01(\x03R\x17serverTimestampUnixNano2S\n" +
	"\fSidecarAdmin\x12C\n" +
	"\bRegister\x12\x18.sidecar.RegisterRequest\x1a\x19.sidecar.RegisterResponse(\x010\x01B5Z3github.com/cloudwebrtc/nats-grpc/pkg/protos/sidecarb\x06proto3"

var (
	file_sidecar_sidecar_proto_rawDescOnce sync.Once
	file_sidecar_sidecar_proto_rawDescData []byte
)

func file_sidecar_sidecar_proto_rawDescGZIP() []byte {
	file_sidecar_sidecar_proto_rawDescOnce.Do(func() {
		file_sidecar_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sidecar_sidecar_proto_rawDesc), len(file_sidecar_sidecar_proto_rawDesc)))
	})
	return file_sidecar_sidecar_proto_rawDescData
}

var file_sidecar_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sidecar_sidecar_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: sidecar.RegisterRequest
	(*Init)(nil),             // 1: sidecar.Init
	(*Heartbeat)(nil),        // 2: sidecar.Heartbeat
	(*RegisterResponse)(nil), // 3: sidecar.RegisterResponse
	(*Registered)(nil),       // 4: sidecar.Registered
	(*ErrorResponse)(nil),    // 5: sidecar.ErrorResponse
	(*HeartbeatAck)(nil),     // 6: sidecar.HeartbeatAck
}
var file_sidecar_sidecar_proto_depIdxs = []int32{
	1, // 0: sidecar.RegisterRequest.init:type_name -> sidecar.Init
	2, // 1: sidecar.RegisterRequest.heartbeat:type_name -> sidecar.Heartbeat
	4, // 2: sidecar.RegisterResponse.registered:type_name -> sidecar.Registered
	5, // 3: sidecar.RegisterResponse.error:type_name -> sidecar.ErrorResponse
	6, // 4: sidecar.RegisterResponse.heartbeat_ack:type_name -> sidecar.HeartbeatAck
	0, // 5: sidecar.SidecarAdmin.Register:input_type -> sidecar.RegisterRequest
	3, // 6: sidecar.SidecarAdmin.Register:output_type -> sidecar.RegisterResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sidecar_sidecar_proto_init() }
func file_sidecar_sidecar_proto_init() {
	if File_sidecar_sidecar_proto != nil {
		return
	}
	file_sidecar_sidecar_proto_msgTypes[0].OneofWrappers = []any{
		(*RegisterRequest_Init)(nil),
		(*RegisterRequest_Heartbeat)(nil),
	}
	file_sidecar_sidecar_proto_msgTypes[3].OneofWrappers = []any{
		(*RegisterResponse_Registered)(nil),
		(*RegisterResponse_Error)(nil),
		(*RegisterResponse_HeartbeatAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidecar_sidecar_proto_rawDesc), len(file_sidecar_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sidecar_sidecar_proto_goTypes,
		DependencyIndexes: file_sidecar_sidecar_proto_depIdxs,
		MessageInfos:      file_sidecar_sidecar_proto_msgTypes,
	}.Build()
	File_sidecar_sidecar_proto = out.File
	file_sidecar_sidecar_proto_goTypes = nil
	file_sidecar_sidecar_proto_depIdxs = nil
}
