// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.1
// source: sidecar/sidecar.proto

package sidecar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SidecarAdmin_Register_FullMethodName = "/sidecar.SidecarAdmin/Register"
)

// SidecarAdminClient is the client API for SidecarAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SidecarAdmin lets a local app register itself with the sidecar's ingress
// dispatcher. The svcid is determined dynamically at app startup (e.g. from
// env / claim / tenant config), so registration cannot be expressed as
// static sidecar config.
//
// Lease semantics: the Register stream IS the lease. Holding it open keeps
// the registration alive; closing it (or crashing) deregisters everything
// associated with the stream — including tearing down NATS subscriptions
// and aborting in-flight ingress RPCs against the upstream.
type SidecarAdminClient interface {
	// Register opens a long-lived bidi stream. The first client message
	// must be Init; the server replies with Registered (containing the
	// sidecar-assigned nid). The client may then send periodic
	// Heartbeats for application-level liveness. Server-initiated
	// teardown is not expressed in the protocol — drop the stream to
	// deregister.
	Register(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterRequest, RegisterResponse], error)
}

type sidecarAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewSidecarAdminClient(cc grpc.ClientConnInterface) SidecarAdminClient {
	return &sidecarAdminClient{cc}
}

func (c *sidecarAdminClient) Register(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterRequest, RegisterResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SidecarAdmin_ServiceDesc.Streams[0], SidecarAdmin_Register_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterRequest, RegisterResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SidecarAdmin_RegisterClient = grpc.BidiStreamingClient[RegisterRequest, RegisterResponse]

// SidecarAdminServer is the server API for SidecarAdmin service.
// All implementations must embed UnimplementedSidecarAdminServer
// for forward compatibility.
//
// SidecarAdmin lets a local app register itself with the sidecar's ingress
// dispatcher. The svcid is determined dynamically at app startup (e.g. from
// env / claim / tenant config), so registration cannot be expressed as
// static sidecar config.
//
// Lease semantics: the Register stream IS the lease. Holding it open keeps
// the registration alive; closing it (or crashing) deregisters everything
// associated with the stream — including tearing down NATS subscriptions
// and aborting in-flight ingress RPCs against the upstream.
type SidecarAdminServer interface {
	// Register opens a long-lived bidi stream. The first client message
	// must be Init; the server replies with Registered (containing the
	// sidecar-assigned nid). The client may then send periodic
	// Heartbeats for application-level liveness. Server-initiated
	// teardown is not expressed in the protocol — drop the stream to
	// deregister.
	Register(grpc.BidiStreamingServer[RegisterRequest, RegisterResponse]) error
	mustEmbedUnimplementedSidecarAdminServer()
}

// UnimplementedSidecarAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSidecarAdminServer struct{}

func (UnimplementedSidecarAdminServer) Register(grpc.BidiStreamingServer[RegisterRequest, RegisterResponse]) error {
	return status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSidecarAdminServer) mustEmbedUnimplementedSidecarAdminServer() {}
func (UnimplementedSidecarAdminServer) testEmbeddedByValue()                      {}

// UnsafeSidecarAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SidecarAdminServer will
// result in compilation errors.
type UnsafeSidecarAdminServer interface {
	mustEmbedUnimplementedSidecarAdminServer()
}

func RegisterSidecarAdminServer(s grpc.ServiceRegistrar, srv SidecarAdminServer) {
	// If the following call panics, it indicates UnimplementedSidecarAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SidecarAdmin_ServiceDesc, srv)
}

func _SidecarAdmin_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SidecarAdminServer).Register(&grpc.GenericServerStream[RegisterRequest, RegisterResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SidecarAdmin_RegisterServer = grpc.BidiStreamingServer[RegisterRequest, RegisterResponse]

// SidecarAdmin_ServiceDesc is the grpc.ServiceDesc for SidecarAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SidecarAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sidecar.SidecarAdmin",
	HandlerType: (*SidecarAdminServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _SidecarAdmin_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sidecar/sidecar.proto",
}
