{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats-grpc-benchmark.fullname" . }}-server
  labels:
    app: {{ include "nats-grpc-benchmark.name" . }}-server
    chart: {{ include "nats-grpc-benchmark.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "nats-grpc-benchmark.name" . }}-server
    release: {{ .Release.Name }}
{{- end }}
