{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nats-grpc-benchmark.fullname" . }}-server
  labels:
    app: {{ include "nats-grpc-benchmark.name" . }}-server
    chart: {{ include "nats-grpc-benchmark.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "nats-grpc-benchmark.name" . }}-server
      release: {{ .Release.Name }}
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nats-grpc-benchmark.fullname" . }}-client
  labels:
    app: {{ include "nats-grpc-benchmark.name" . }}-client
    chart: {{ include "nats-grpc-benchmark.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "nats-grpc-benchmark.name" . }}-client
      release: {{ .Release.Name }}
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: /metrics
{{- end }}
