// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: nrpc/nrpc.proto

package nrpc

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Request_Call
	//	*Request_Data
	//	*Request_End
	//	*Request_Ping
	//	*Request_Unary
	Type          isRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_nrpc_nrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetType() isRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Request) GetCall() *Call {
	if x != nil {
		if x, ok := x.Type.(*Request_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *Request) GetData() *Data {
	if x != nil {
		if x, ok := x.Type.(*Request_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Request) GetEnd() *End {
	if x != nil {
		if x, ok := x.Type.(*Request_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *Request) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Type.(*Request_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Request) GetUnary() *UnaryRequest {
	if x != nil {
		if x, ok := x.Type.(*Request_Unary); ok {
			return x.Unary
		}
	}
	return nil
}

type isRequest_Type interface {
	isRequest_Type()
}

type Request_Call struct {
	Call *Call `protobuf:"bytes,2,opt,name=call,proto3,oneof"`
}

type Request_Data struct {
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Request_End struct {
	End *End `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

type Request_Ping struct {
	Ping *Ping `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

type Request_Unary struct {
	Unary *UnaryRequest `protobuf:"bytes,6,opt,name=unary,proto3,oneof"`
}

func (*Request_Call) isRequest_Type() {}

func (*Request_Data) isRequest_Type() {}

func (*Request_End) isRequest_Type() {}

func (*Request_Ping) isRequest_Type() {}

func (*Request_Unary) isRequest_Type() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Response_Begin
	//	*Response_Data
	//	*Response_End
	//	*Response_Pong
	//	*Response_Unary
	Type          isResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_nrpc_nrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetType() isResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Response) GetBegin() *Begin {
	if x != nil {
		if x, ok := x.Type.(*Response_Begin); ok {
			return x.Begin
		}
	}
	return nil
}

func (x *Response) GetData() *Data {
	if x != nil {
		if x, ok := x.Type.(*Response_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Response) GetEnd() *End {
	if x != nil {
		if x, ok := x.Type.(*Response_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *Response) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Type.(*Response_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Response) GetUnary() *UnaryResponse {
	if x != nil {
		if x, ok := x.Type.(*Response_Unary); ok {
			return x.Unary
		}
	}
	return nil
}

type isResponse_Type interface {
	isResponse_Type()
}

type Response_Begin struct {
	Begin *Begin `protobuf:"bytes,2,opt,name=begin,proto3,oneof"`
}

type Response_Data struct {
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Response_End struct {
	End *End `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

type Response_Pong struct {
	Pong *Pong `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

type Response_Unary struct {
	Unary *UnaryResponse `protobuf:"bytes,6,opt,name=unary,proto3,oneof"`
}

func (*Response_Begin) isResponse_Type() {}

func (*Response_Data) isResponse_Type() {}

func (*Response_End) isResponse_Type() {}

func (*Response_Pong) isResponse_Type() {}

func (*Response_Unary) isResponse_Type() {}

// UnaryRequest bundles Call + Data into a single message so unary RPCs can be
// served via NATS request/reply (queue-group load-balanced).
type UnaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryRequest) Reset() {
	*x = UnaryRequest{}
	mi := &file_nrpc_nrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryRequest) ProtoMessage() {}

func (x *UnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryRequest.ProtoReflect.Descriptor instead.
func (*UnaryRequest) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{2}
}

func (x *UnaryRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UnaryRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UnaryRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UnaryResponse carries the full reply for a unary RPC in one message.
type UnaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Metadata              `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Trailer       *Metadata              `protobuf:"bytes,2,opt,name=trailer,proto3" json:"trailer,omitempty"`
	Status        *status.Status         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryResponse) Reset() {
	*x = UnaryResponse{}
	mi := &file_nrpc_nrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryResponse) ProtoMessage() {}

func (x *UnaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryResponse.ProtoReflect.Descriptor instead.
func (*UnaryResponse) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{3}
}

func (x *UnaryResponse) GetHeader() *Metadata {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UnaryResponse) GetTrailer() *Metadata {
	if x != nil {
		return x.Trailer
	}
	return nil
}

func (x *UnaryResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UnaryResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Strings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Strings) Reset() {
	*x = Strings{}
	mi := &file_nrpc_nrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strings) ProtoMessage() {}

func (x *Strings) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strings.ProtoReflect.Descriptor instead.
func (*Strings) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{4}
}

func (x *Strings) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Md            map[string]*Strings    `protobuf:"bytes,1,rep,name=md,proto3" json:"md,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_nrpc_nrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{5}
}

func (x *Metadata) GetMd() map[string]*Strings {
	if x != nil {
		return x.Md
	}
	return nil
}

type Call struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Nid           string                 `protobuf:"bytes,3,opt,name=nid,proto3" json:"nid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_nrpc_nrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{6}
}

func (x *Call) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Call) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Call) GetNid() string {
	if x != nil {
		return x.Nid
	}
	return ""
}

type Begin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Metadata              `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Nid           string                 `protobuf:"bytes,2,opt,name=nid,proto3" json:"nid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Begin) Reset() {
	*x = Begin{}
	mi := &file_nrpc_nrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Begin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Begin) ProtoMessage() {}

func (x *Begin) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Begin.ProtoReflect.Descriptor instead.
func (*Begin) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{7}
}

func (x *Begin) GetHeader() *Metadata {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Begin) GetNid() string {
	if x != nil {
		return x.Nid
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_nrpc_nrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{8}
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type End struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Trailer       *Metadata              `protobuf:"bytes,2,opt,name=trailer,proto3" json:"trailer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *End) Reset() {
	*x = End{}
	mi := &file_nrpc_nrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *End) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*End) ProtoMessage() {}

func (x *End) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use End.ProtoReflect.Descriptor instead.
func (*End) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{9}
}

func (x *End) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *End) GetTrailer() *Metadata {
	if x != nil {
		return x.Trailer
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_nrpc_nrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{10}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_nrpc_nrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_nrpc_nrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_nrpc_nrpc_proto_rawDescGZIP(), []int{11}
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_nrpc_nrpc_proto protoreflect.FileDescriptor

const file_nrpc_nrpc_proto_rawDesc = "" +
	"\n" +
	"\x0fnrpc/nrpc.proto\x12\x04nrpc\x1a\x17google/rpc/status.proto\"\xc2\x01\n" +
	"\aRequest\x12 \n" +
	"\x04call\x18\x02 \x01(\v2\n" +
	".nrpc.CallH\x00R\x04call\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\n" +
	".nrpc.DataH\x00R\x04data\x12\x1d\n" +
	"\x03end\x18\x04 \x01(\v2\t.nrpc.EndH\x00R\x03end\x12 \n" +
	"\x04ping\x18\x05 \x01(\v2\n" +
	".nrpc.PingH\x00R\x04ping\x12*\n" +
	"\x05unary\x18\x06 \x01(\v2\x12.nrpc.UnaryRequestH\x00R\x05unaryB\x06\n" +
	"\x04type\"\xc7\x01\n" +
	"\bResponse\x12#\n" +
	"\x05begin\x18\x02 \x01(\v2\v.nrpc.BeginH\x00R\x05begin\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\n" +
	".nrpc.DataH\x00R\x04data\x12\x1d\n" +
	"\x03end\x18\x04 \x01(\v2\t.nrpc.EndH\x00R\x03end\x12 \n" +
	"\x04pong\x18\x05 \x01(\v2\n" +
	".nrpc.PongH\x00R\x04pong\x12+\n" +
	"\x05unary\x18\x06 \x01(\v2\x13.nrpc.UnaryResponseH\x00R\x05unaryB\x06\n" +
	"\x04type\"f\n" +
	"\fUnaryRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12*\n" +
	"\bmetadata\x18\x02 \x01(\v2\x0e.nrpc.MetadataR\bmetadata\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xa1\x01\n" +
	"\rUnaryResponse\x12&\n" +
	"\x06header\x18\x01 \x01(\v2\x0e.nrpc.MetadataR\x06header\x12(\n" +
	"\atrailer\x18\x02 \x01(\v2\x0e.nrpc.MetadataR\atrailer\x12*\n" +
	"\x06status\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x06status\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"!\n" +
	"\aStrings\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"x\n" +
	"\bMetadata\x12&\n" +
	"\x02md\x18\x01 \x03(\v2\x16.nrpc.Metadata.MdEntryR\x02md\x1aD\n" +
	"\aMdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.nrpc.StringsR\x05value:\x028\x01\"\\\n" +
	"\x04Call\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12*\n" +
	"\bmetadata\x18\x02 \x01(\v2\x0e.nrpc.MetadataR\bmetadata\x12\x10\n" +
	"\x03nid\x18\x03 \x01(\tR\x03nid\"A\n" +
	"\x05Begin\x12&\n" +
	"\x06header\x18\x01 \x01(\v2\x0e.nrpc.MetadataR\x06header\x12\x10\n" +
	"\x03nid\x18\x02 \x01(\tR\x03nid\"\x1a\n" +
	"\x04Data\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"[\n" +
	"\x03End\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12(\n" +
	"\atrailer\x18\x02 \x01(\v2\x0e.nrpc.MetadataR\atrailer\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestampB2Z0github.com/cloudwebrtc/nats-grpc/pkg/protos/nrpcb\x06proto3"

var (
	file_nrpc_nrpc_proto_rawDescOnce sync.Once
	file_nrpc_nrpc_proto_rawDescData []byte
)

func file_nrpc_nrpc_proto_rawDescGZIP() []byte {
	file_nrpc_nrpc_proto_rawDescOnce.Do(func() {
		file_nrpc_nrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nrpc_nrpc_proto_rawDesc), len(file_nrpc_nrpc_proto_rawDesc)))
	})
	return file_nrpc_nrpc_proto_rawDescData
}

var file_nrpc_nrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_nrpc_nrpc_proto_goTypes = []any{
	(*Request)(nil),       // 0: nrpc.Request
	(*Response)(nil),      // 1: nrpc.Response
	(*UnaryRequest)(nil),  // 2: nrpc.UnaryRequest
	(*UnaryResponse)(nil), // 3: nrpc.UnaryResponse
	(*Strings)(nil),       // 4: nrpc.Strings
	(*Metadata)(nil),      // 5: nrpc.Metadata
	(*Call)(nil),          // 6: nrpc.Call
	(*Begin)(nil),         // 7: nrpc.Begin
	(*Data)(nil),          // 8: nrpc.Data
	(*End)(nil),           // 9: nrpc.End
	(*Ping)(nil),          // 10: nrpc.Ping
	(*Pong)(nil),          // 11: nrpc.Pong
	nil,                   // 12: nrpc.Metadata.MdEntry
	(*status.Status)(nil), // 13: google.rpc.Status
}
var file_nrpc_nrpc_proto_depIdxs = []int32{
	6,  // 0: nrpc.Request.call:type_name -> nrpc.Call
	8,  // 1: nrpc.Request.data:type_name -> nrpc.Data
	9,  // 2: nrpc.Request.end:type_name -> nrpc.End
	10, // 3: nrpc.Request.ping:type_name -> nrpc.Ping
	2,  // 4: nrpc.Request.unary:type_name -> nrpc.UnaryRequest
	7,  // 5: nrpc.Response.begin:type_name -> nrpc.Begin
	8,  // 6: nrpc.Response.data:type_name -> nrpc.Data
	9,  // 7: nrpc.Response.end:type_name -> nrpc.End
	11, // 8: nrpc.Response.pong:type_name -> nrpc.Pong
	3,  // 9: nrpc.Response.unary:type_name -> nrpc.UnaryResponse
	5,  // 10: nrpc.UnaryRequest.metadata:type_name -> nrpc.Metadata
	5,  // 11: nrpc.UnaryResponse.header:type_name -> nrpc.Metadata
	5,  // 12: nrpc.UnaryResponse.trailer:type_name -> nrpc.Metadata
	13, // 13: nrpc.UnaryResponse.status:type_name -> google.rpc.Status
	12, // 14: nrpc.Metadata.md:type_name -> nrpc.Metadata.MdEntry
	5,  // 15: nrpc.Call.metadata:type_name -> nrpc.Metadata
	5,  // 16: nrpc.Begin.header:type_name -> nrpc.Metadata
	13, // 17: nrpc.End.status:type_name -> google.rpc.Status
	5,  // 18: nrpc.End.trailer:type_name -> nrpc.Metadata
	4,  // 19: nrpc.Metadata.MdEntry.value:type_name -> nrpc.Strings
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_nrpc_nrpc_proto_init() }
func file_nrpc_nrpc_proto_init() {
	if File_nrpc_nrpc_proto != nil {
		return
	}
	file_nrpc_nrpc_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Call)(nil),
		(*Request_Data)(nil),
		(*Request_End)(nil),
		(*Request_Ping)(nil),
		(*Request_Unary)(nil),
	}
	file_nrpc_nrpc_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_Begin)(nil),
		(*Response_Data)(nil),
		(*Response_End)(nil),
		(*Response_Pong)(nil),
		(*Response_Unary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nrpc_nrpc_proto_rawDesc), len(file_nrpc_nrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nrpc_nrpc_proto_goTypes,
		DependencyIndexes: file_nrpc_nrpc_proto_depIdxs,
		MessageInfos:      file_nrpc_nrpc_proto_msgTypes,
	}.Build()
	File_nrpc_nrpc_proto = out.File
	file_nrpc_nrpc_proto_goTypes = nil
	file_nrpc_nrpc_proto_depIdxs = nil
}
